version: '3'

services:
  db:
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: <%= Rails.application.credentials.dig(:postgresql, :user) %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.dig(:postgresql, :password) %>

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true 
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3001:3000"
    volumes:
      - .:/design_support
    environment:
      DATABASE_PASSWORD: <%= Rails.application.credentials.dig(:postgresql, :password) %>

volumes:
  postgresql-data:
