sorcery:
  twitter_callback_url: 'http://127.0.0.1:3000/oauth/callback?provider=twitter'
  google_callback_url: 'http://localhost:3001/oauth/callback?provider=google'

default_url_options:
  host: 'localhost:3001'