sorcery:
  twitter_callback_url: 'https://www.anyone-design.com/oauth/callback?provider=twitter'
  google_callback_url: 'https://www.anyone-design.com/oauth/callback?provider=google'

default_url_options:
  protocol: 'https'
  host: 'anyone-design.com'